### ISSUE TITLE
Grade attribute on Excel exported report not showing up correctly

### ISSUE THREAD

**Issue by cartervillecc** [SparkDevNetwork/Rock#1216]
I am exporting a report with "Grade" selected as one of the fields. When looking at the grid in ROCK, the "Grade" shows up fine, but once I export it and open it in Excel, it shows the "Graduation Year" and not "Grade." Ex: In Excel, Kindergarten becomes 2028.
<img width="1189" alt="screen shot 2015-08-31 at 9 06 07 am" src="https://cloud.githubusercontent.com/assets/14056020/9580624/30c49b00-4fc0-11e5-9bbb-a5ed34e81a62.png">
<img width="545" alt="screen shot 2015-08-31 at 9 07 24 am" src="https://cloud.githubusercontent.com/assets/14056020/9580633/36e00ad8-4fc0-11e5-8f56-66d7ddb1e640.png">

**Comment by MrUpsideDown** [comment]
This is causing problems for us too.
@azturner I am currently working on a fix for this.

**Comment by cartervillecc** [comment]
Thank you!

**Comment by garrettjohnson** [comment]
@nairdo Is the code that generates the grid similar to what you fixed in #1946? I can't find the code where this transformation is happening.

**Comment by nairdo** [comment]
@garrettjohnson no, but although I haven't fully debugged this, I _think_ this has to with what the GradeSelect (a DataSelectComponent) is returning for the grade expression: 
https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Reporting/DataSelect/Person/GradeSelect.cs#L160

**Comment by nairdo** [comment]
I just did a test in the current develop branch and it looks like this is fixed.  Perhaps whoever fixed it didn't realize there was an issue associated with this bug because there's no reference to this issue # in the commit.

I'm going to close this as fixed -- but I have no idea exactly which version fixed it.

**Comment by knolly42** [comment]
This is still an issue sadly, well at least on McKinley 6.7. Has anyone managed to track down a manual fix for it at all please?

We are setting up to go live in September this year and wanted to use the Excel export for our kids ministry where WiFi is not guaranteed.

Any guidance would be really appreciated thanks

**Comment by azturner** [comment]
@knolly42 This will be fixed in the v7 release. Until then, you can use a Lava field to display and export the grade correctly:
![reports rock rms](https://user-images.githubusercontent.com/548180/28686383-e4deaeae-72bf-11e7-9baf-a237245dd0a5.png)
(You do need to include the ID column, but it can be hidden)

**Comment by knolly42** [comment]
Oh Wow!! THANKSSS!!!

Now I can rest up for the remainder of my evening..

So grateful, God bless you
