### ISSUE TITLE
Group Registration lets you register into any group (even RSR - Rock Administration)

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#1799]
### Description

The group registration block has no permissions for what groups should be allowed to be registered for, and you can change the group by just changing it's id in the url. This allows a person to register themselves into any group, including security roles such as RSR - Rock Administration (Though security roles will need to wait for the cache to update).

### Steps to Reproduce

1. Create an account
2. Find a group registration block
3. Change the GroupId in the url to '2' and register yourself
6. You are now in the RSR - Rock Administration group, and if the Group Member Status was set to Active in the block settings, you'll have full control of Rock as soon as the cache updates.

**Expected behavior:** 
A message would appear saying that this group isn't open to registration.

**Actual behavior:** 
You can add yourself to any group.

### Versions

* **Rock Version:** 5.4

**Comment by JimMichael** [comment]
No one else thinks this is a defcon-5 level bug? :-)

**Comment by edmistj** [comment]
Was fixed in this commit https://github.com/SparkDevNetwork/Rock/commit/6e313a969f44fd9b3d0c3344955806d73da3b609 on the same day as the issue (sorry that it wasn't updated, should have been). The fix:

+ Allows linking by Guid
+ Will not allow adding to a security role
+ We had to leave the ability to link by Id as we'd break a lot of people, but hope that the disallowing updating security roles would fix the major issue.

You can download the fix here. 
https://rockrms.blob.core.windows.net/misc/GroupRegistrationFix.zip

Apply the files to ~/Blocks/Groups

**Comment by Tschrock** [comment]
:/  Hmm.. that's still just a patch though. Doesn't solve the actual issue that you can put yourself into groups you shouldn't be in.

For example, we have groups (not security roles) for the staff page on our website, and this wouldn't stop anyone from adding themselves to that group and showing up as a staff member on the site. Or placing themselves into a volunteer/children's check-in group that would let them check into a secure children's environment. Or adding themselves to a group for a paid event. Or adding themselves to a family to gain access to view or change all of their info.

And this still allows scraping any of the group details shown for all of your groups (There's no View permission checking).

And while using a GUID helps, it doesn't *fix* the problem - it just obscures it.
I can also think of at least one (albeit very minor) use-case for allowing registering for a security group.

**Comment by JimMichael** [comment]
would the public checkbox help with this kind of thing? If the group isn't made public, it can't be joined? I also don't think a guid is necesssriky hiding the problem. You'd have to know an existing guid to "guess" a match.

**Comment by JimMichael** [comment]
Er, meant to say you'd have to know an existing guid because guessing and getting a match is pretty crazy unlikely.
