### ISSUE TITLE
Check-in screen not displaying countdown

### ISSUE THREAD

**Issue by dave-sccc** [SparkDevNetwork/Rock#2656]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently using version 7.0.  Using international (Australian) date format "dd/mm/yyyy" for database and local regional settings.
Since updates around September last year (can't be sure of the version, sorry), the check-in welcome screen stopped displaying the countdown for future schedules and instead displayed the message "There are no current or future schedules for this kiosk today!".  Originally I just continued to use the old welcome.ascx.cs file and this resolved the problem.  That no longer works in version 7.
Once the check-in start time is reached it correctly displays the Start button.

Upon further investigations I have discovered that the font size of this message changes (get's smaller) if there is an upcoming schedule for that day compared to if there isn't (larger - see screenshots).

![screenshot 1](https://user-images.githubusercontent.com/28860251/34758810-73db2fb8-f5d0-11e7-9a93-67ee348ffc88.png)
![screenshot 2](https://user-images.githubusercontent.com/28860251/34758811-7418602c-f5d0-11e7-822f-1e375c8e44b1.png)

This problem occurs regardless of whether or not the IP address is set in the devices configuration (though separate bug there in 7.0beta that I'm getting a Unable to find an entry point named 'SetClrFeatureSwitchMap' in DLL 'SqlServerSpatial110.dll'. when trying to add or change a device).

### Steps to Reproduce

1. Set up and enable schedule for today's date but at a time later than the current time + enable check-in before time.
2. Load the check-in page

**Expected behavior:** 

Page to provide a countdown until check-in opens.

**Actual behavior:** 

Page reports "There are no current or future schedules for this kiosk today!".

### Versions

* **Rock Version:** [7.0]  
* **Client Culture Setting:** [EN-AU]

**Comment by mikejed** [comment]
We too have had this issue since installing v1.6.9. We have also confirmed that updating to 1.6.10 and 1.7.0 does not resolve the issue. We had not found the workaround of using the old version of the file, nor had we noted the font size change.

**Comment by JimMichael** [comment]
Looks like it's fixed here https://github.com/SparkDevNetwork/Rock/issues/2570 (and someone fibbed about doing that cursory search) :-p

**Comment by edmistj** [comment]
@dave-sccc would you be able to confirm that that fix addresses the issue?

**Comment by dave-sccc** [comment]
As stated in my original report (under the screenshots), this did not resolve the problem.
Despite the separate problem I mentioned when changing or adding devices, I was easily able to test this using IPs already in my devices list.

(Sorry @JimMichael, I did the cursory search. Looks like someone didn't read my post fully.)

**Comment by mikejed** [comment]
I'm testing the changes made in commit 45b9f32 but so far it does not appear to have worked, either

**Comment by dave-sccc** [comment]
I had also tried this with no success before logging the bug.

**Comment by mikejed** [comment]
Oops! I hadn't hit "Save" on the schedule. Commit 45b9f32 fixed the issue for us on 1.6.9

**Comment by dave-sccc** [comment]
I'll relook at it then in case my other mods were interfering. Will confirm shortly.

**Comment by dave-sccc** [comment]
Grrr, can't believe I missed that... I was still using part of the old file when applying the fix.
Works now. Sorry to waste people's time. Confirmed will be fixed with changes in 7.1

**Comment by edmistj** [comment]
No problem. Thanks for working through it.
