### ISSUE TITLE
Event Registrations are not creating person notes - v7

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#2676]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When an event registration has the Add Person Note box checked, notes are not showing up on the person page. This seems to only be an issue if the registrant is not matched to an existing person. 

### Steps to Reproduce

1. Set up an event registration and check the yes box for Add Person Note
2. Register someone for the event

**Expected behavior:** 

When viewing the person page, a person note would show that they registered for the event

**Actual behavior:** 

No note

### Versions

* **Rock Version:** 7.0
* **Client Culture Setting:** en-us

**Comment by KelleyLangkamp** [comment]
This is fixed in the 7.1 beta. I'm assuming the fix for another issue also fixed this.

**Comment by luke-b-taylor** [comment]
I'm still seeing this issue on 7.2 when the person doing the registration is logged in.  Doesn't seem to happen otherwise

**Comment by edmistj** [comment]
Is someone else able to confirm this?

**Comment by JimMichael** [comment]
I cannot dupe on 7.2. I registered for a (no pay) event here (which prompted for login) and the note was added to my record as usual.

**Comment by luke-b-taylor** [comment]
What I've seen is when there's a separate registrar and registrant.  In this case, today, mom who works here registered her son, neither received a note.   Add person note is checked.

**Comment by JimMichael** [comment]
Further testing here... 

1. On a brand new registration I've never signed up for, registered myself and wife (while I was authenticated). Both of us got the expected "registered for event by James Michael" notes. I additionally got the "Registered Anissa Michael for Event" note added to my profile.

2. I went back to the prior registration (where I registered only myself, on which I got the note) and registered my wife. She did NOT get the expected note, nor did I get the note on my record saying I registered her.

So perhaps the failure mode is only when you're logged in and registering someone else _besides_ yourself (vs. in-addition-to yourself, which works for me)

**Comment by baynehh** [comment]
We are seeing this issue on 7.3 with parents registering kids for camps.

**Comment by arranf** [comment]
Reproduced in 8.0

**Comment by arranf** [comment]
The `RegistrantDetail` block does not appear to add any notes when registrants are added internally. I don't think this is the only avenue where notes are not being applied though.

**Comment by arranf** [comment]
In `RegistrationDetail` in the case a logged in person adds registrants the `Registration.PersonAlias` is not being populated which is causing this bug.
