### ISSUE TITLE
Group / GroupMember not available in Merge Template

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2726]
### Description

Using the default [Group Attendance Roster](http://rock.rocksolidchurchdemo.com/page/5314?MergeTemplateId=6&ExpandedIds=C6164) merge document, the Lava header for `{{ Group.Name }}` does not resolve from a Group Member list.

![screenshot 2018-02-01 14 23 30](https://user-images.githubusercontent.com/1210933/35698594-8d35c184-075b-11e8-8246-1a4c249a544f.png)

![screenshot 2018-02-01 14 36 07](https://user-images.githubusercontent.com/1210933/35699171-4743ca0c-075d-11e8-94d5-dd4a450da0a2.png)

![screenshot 2018-02-01 14 38 42](https://user-images.githubusercontent.com/1210933/35699297-9daf148c-075d-11e8-9192-f6c4a862b1f9.png)

### v6 Troubleshooting:

Lava Debug Info shows GroupMember with a Group attached to it, but I couldn't find a Lava variation that worked: `Row.GroupMember.Group.Name`, `Row | First | GroupMember | Group | Property:'Name'`

![screenshot 2018-02-01 14 26 45](https://user-images.githubusercontent.com/1210933/35698825-38367a74-075c-11e8-8dd9-507f106fd2d4.png)

### v7 Troubleshooting:

Lava Debug Info throws an error on the GroupMember object:

![screenshot 2018-02-01 14 18 47](https://user-images.githubusercontent.com/1210933/35698837-3ec81c30-075c-11e8-89d4-4867d77c4ed4.png)

### Steps to Reproduce

1. Select Merge Document from a Group Viewer list 
2. Choose the Group Attendance Roster merge document
3. Open the downloaded merge document

**Expected behavior:** 

The header should list Group.Name and Date

**Actual behavior:** 

The header lists Date but not Group Name

### Possible Resolution

Based on the `Group.Name` syntax, I would expect the Group object is part of the mergeObjectsDictionary in [MergeTemplateEntry](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Core/MergeTemplateEntry.ascx.cs#L371), but that isn't the case.  

Adding that Group object may be the easiest fix moving forward.

### Versions

* **Rock Version:** v6-v7
* **Client Culture Setting:** en-us

**Comment by MikeDPeterson** [comment]
@dcs619 The GroupMember lava help issue has been fixed, and there were some other Person fields that were also throwing an exception.  However, doing {{ row.GroupMember.Group.Name }} should still work.  Here is a new sample merge template that does this: https://github.com/SparkDevNetwork/Rock/blob/develop/Dev%20Tools/Sample%20Merge%20Templates/PersonGroupMemberGroupHtmlTemplate.html

**Comment by dylan-gregory** [comment]
I've seen this issue resurface - in both v8 (tested in 8.7) and v9 (tested in 9.2).

**Comment by pokes2k** [comment]
Looks like this is still happening, even on the Rock Demo site in 14.2. I can confirm that it's happening in 13.7. The group name field shows up blank in the header whether it's {{ Group.Name }} as the example shows, or {{ row.GroupMember.Group.Name }} as suggested above.

**Comment by nairdo** [comment]
@pokes2k  Thanks for letting us know.  I'll re-open and we'll take a look at this one again.

**Comment by pokes2k** [comment]
Thank you, @nairdo. To add more info, we actually got {{ Row.GroupMember.Group.Name }} to work in the body of the template but it will not work in the header as designed in the example. The 'Now' date code works just fine.
