### ISSUE TITLE
v7.1: DynamicReport block labels initially missing

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2746]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Existing DynamicReport blocks visually lose their labels in the upgrade from 1.7.0 to 1.7.1.

Editing the block settings and clicking save causes the default `{{ Label }}` values to work correctly and show up, but initially the reports look like this:
![image](https://user-images.githubusercontent.com/6932047/35941450-7d76b376-0c0f-11e8-86de-8cfc1a0301aa.png)

### Steps to Reproduce

1. Ensure a Dynamic Report block exists in Rock v1.7.0 (or earlier)
2. Update to v1.7.1 (or 1.7.2)
3. View the Dynamic Report block and note the missing labels

**Expected behavior:** 

The new default `{{ Label }}` contents should allow the same label to come through as the page showed previously

**Actual behavior:** 

The labels are missing until you save the block settings

### Versions

* **Rock Version:** 1.7.1, 1.7.2  
* **Client Culture Setting:** EN-US

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/dab109864ed50827c2d31faf76c200cf3d9745de

**Comment by tommyprater** [comment]
I just upgraded to v7.3 and still experiencing this issue after upgrade. I can edit that block and click save then the labels appear.

**Comment by mikejed** [comment]
It should be noted that on the demo server today, I created a dynamic report under 6.2. Then I upgraded to 6.10, then to 7.0. Checked and the report labels were fine. Then upgraded straight to 7.3 and checked again, and found the labels were still fine.

Just offering a data point

**Comment by edmistj** [comment]
@tommyprater can you re-confirm this and re-open if you still have the issue.
