### ISSUE TITLE
Event Registration Form using Person Field "Connection Status" does not display on Registrant results grid

### ISSUE THREAD

**Issue by jgrabrian** [SparkDevNetwork/Rock#3224]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When adding a Person Field "Connection Status" to a form in any registration template, the column is not displayed in the Registrant results grid. Any other Person Field displays fine when "show on grid" is selected.

### Steps to Reproduce
1. Go to any Registration Template already created
1. Click on EDIT
1. Scroll down to Form
1. Add an attribute with the following criteria:
 a. Source: Person Field
 b. Person Field: 'Connection Status'
 d. Show on Grid: Yes
 e. Use Current Value: Yes

![image](https://user-images.githubusercontent.com/383807/56587215-ff57fe00-6595-11e9-971b-2f4000011e49.png)

**Expected behavior:**

The "Connection Status" for registrants should be displayed as a column in the Event Instance - Registrant tab.

**Actual behavior:**

The column "Connection Status" does not display in the Registrants results grid

![image](https://user-images.githubusercontent.com/383807/56587240-0848cf80-6596-11e9-8164-d7f6fc80fa13.png)

### Versions
* **Rock Version:** [7.4, 7.5, 8.6, 1.9.0.17]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
Pretty sure this is fixed in 8.1 via https://github.com/SparkDevNetwork/Rock/issues/1781

**Comment by jgrabrian** [comment]
OK. I do see in the comments of that issue that it was resolved. Thank You!

**Comment by bobrufenacht** [comment]
This is still an issue in 8.7 and prealpha.  The RegistrationInstanceDetail block does not currently implement Connection Status in the grid even though it is in the list of Person Fields.

**Comment by nairdo** [comment]
Hi Bob, even though as of this fix (https://github.com/SparkDevNetwork/Rock/commit/ee9f7c390819241ae50312b296c1f95b57b22427) we've updated the Help text on on that **Show on Grid** field to state that '_not all person fields are supported_', adding the Connection Status field in there would be OK.  It's just going to require a chunk of code and testing.  You can see the pattern to follow in that commit.
