### ISSUE TITLE
Clicking on menu icons sometimes glitches out (internal theme) when clicking to open menu

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3506]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
When you go to click on a menu icon on the internal site, it tends to "glitch out" and immediately close the popout menu. I assume this is due to the hover effect opening the menu a split second before your click - which then closes the menu again.

[https://www.youtube.com/watch?v=NvWJCb7hvDk](https://www.youtube.com/watch?v=NvWJCb7hvDk)

### Steps to Reproduce
1. Open the internal site
1. Click on one of the menu icons (you might have to adjust your click timing to see it)

**Expected behavior:**

The menu pops out

**Actual behavior:**

The menu flashes up for a split second and then disappears

### Versions
* **Rock Version:** 1.8.5.2, 1.9.0.11 (pre-alpha)
* **Client Culture Setting:** en-US

**Comment by CompassSkelly** [comment]
I tested this on the demo, prealpha, and my dev box running v8.9 on both Chrome and Firefox (which is the browser used in the youtube video) and could not reproduce this bug.  Believed to have been corrected.

**Comment by Tschrock** [comment]
I can still reproduce this on the preapha site on multiple browsers.

Basically there just needs to be a short delay after the hover effect opens the menu so clicking the menu icon doesn't immediately close the menu again

**Comment by CompassSkelly** [comment]
@Tschrock I guess I should read that the action was not quickly hover, but an actual click.  The behavior is the same if you hover for a few moments and then click or if you click right away.  Is this something that come up from multiple users trying to click the navbar or one user?

Either way I believe some kind of onclick action of doing nothing on the Navbar buttons may correct this issue.

**Comment by ethan-sparkdevnetwork** [comment]
The navigation menu is working as designed.
