### ISSUE TITLE
8.6alpha Checkbox Layout

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3514]
### Description

The formatting/layout of checkboxes in 8.6alpha (at least on a Dynamic Report, but I assume other places as well) has a bad appearance vs. 8.5 and prior.

### Steps to Reproduce

1. Create a dynamic report that uses multi-select filters
2. Observe the boxes are all scrunched together on the left and words wrap.

**Expected behavior:**

Layout would be good, like 8.5 and prior.

**Actual behavior:**

It's ugly.

### Versions

* **Rock Version:** 8.6alpha

8.6alpha:
![image](https://user-images.githubusercontent.com/3903408/52018873-7c04a000-24b1-11e9-87a4-35f5944f2d29.png)

8.5:
![image](https://user-images.githubusercontent.com/3903408/52018891-8b83e900-24b1-11e9-9b57-5a372187e87f.png)

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1107508952727764">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1107317347851846">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1108073733557451">checkbox-reflow.gif</a>

**Comment by nairdo** [comment]
Also via https://github.com/sparkdevnetwork/rock/commit/f648df9a716a3f3d68da5f4228051539e247904f.

@JimMichael , can you attach a screenshot of your block & settings?  Although Garrett appears to have been able to reproduce the issue you're reporting here, I'm having a bit of trouble figuring out how you set yours up.

**Comment by JimMichael** [comment]
@nairdo This is the dynamic report
![image](https://user-images.githubusercontent.com/3903408/52159671-32f94b00-266d-11e9-80a3-b38501ce05e5.png)

and this is the DV underlying the report
![image](https://user-images.githubusercontent.com/3903408/52159689-6a67f780-266d-11e9-8fc9-b8038e82008a.png)

**Comment by nairdo** [comment]
I just tested this on a brand new 8.6 alpha install.  Here is what the Dynamic Report filters look like for me on v8.6:
![image](https://user-images.githubusercontent.com/383807/52227879-095b4200-286e-11e9-9cb1-a89705550c1c.png)

... And here's what the **DV filter** looks like for me on 8.6 (looks like "Is" is now "Contains" and there are some additional filter operations too):
![image](https://user-images.githubusercontent.com/383807/52228004-6951e880-286e-11e9-907c-eb34002fbb81.png)

**Comment by nairdo** [comment]
Sorry @JimMichael I should have said that's been fixed in the 8.6 beta (and also in the last three days of the 8.6 alpha -- although we didn't do an official 'second round' of alpha).

**Comment by JimMichael** [comment]
This is still broken for me in 8.6beta
![image](https://user-images.githubusercontent.com/3903408/52503046-fd42ed80-2ba9-11e9-9943-bc2bee9125e0.png)

**Comment by garrettjohnson** [comment]
Fixed in 8.6, looks like the beta build just missed it, but we're updating the beta server now. You can grab the files [_blocks-reporting.less](https://github.com/SparkDevNetwork/Rock/blob/9972bdbf8d4ee3a8384a8bf413606a6237ae59ba/RockWeb/Styles/_blocks-reporting.less) and [theme.less](https://github.com/SparkDevNetwork/Rock/blob/9972bdbf8d4ee3a8384a8bf413606a6237ae59ba/RockWeb/Themes/Rock/Styles/theme.less) if needed immediately
