### ISSUE TITLE
Canon CR-120 Envelope scanning

### ISSUE THREAD

**Issue by ParkerHillIT** [SparkDevNetwork/Rock#3740]
We are rolling out Rock next week, we are set up with the Canon CR-120 check scanner. Checks scan fine, but the envelopes we scan for cash do not register. We get the error "Ranger> Double feed detected". Envelopes scan fine in the Canon app, but it seems this functionality is disabled in the Rock check scanning app. We spoke to Kelly from Kingdom Solutions who recommended posting here. We've experimented with both checking and unchecking the "Enable Double Document Detection" box under scan settings. 
Thanks for the help

Don
Parker Hill Community Church

**Comment by ParkerHillIT** [comment]
Issue was fixed with this updated (rolled back) driver by Silver Bullet Technology Inc.

[www.sbullet.com/temp/AlexM/RangerForCanon-CR120CR150-4.7.1.2-2.1.2.4.zip](url)

After installing the new version you will need to disable double feed detection again.

**Comment by bobrufenacht** [comment]
I have some folks with this issue (again) but the link is broken.  Any chance you still have a copy of the .zip file and could email to bob.rufenacht@bemaservices.com?

**Comment by JoshuaMaiorino** [comment]
This is still an issue with Cannon CR120.  There's nothing on Cannon's Website with the above file listed.

**Comment by JoshuaMaiorino** [comment]
Could this be something that can updated with the pre req in the installer?

**Comment by jonedmiston** [comment]
From what I've been told, we're not allowed to deliver the Silver Bullet drivers. It must be installed from the CD in the box from the scanner.

**Comment by nairdo** [comment]
@bobrufenacht @JoshuaMaiorino Although we're not able to provide Canon Ranger drivers (you have to get them on media that came with the product), we're not certain the issue you're experiencing is with the drivers.  [Although we don't officially support](https://community.rockrms.com/documentation/bookcontent/15/158#supportedscanners) (or have here in our shop) a CR-120, we've heard there is a physical button on them which controls the double-feed detection.  See these two references:

- https://support.usa.canon.com/kb/index?page=content&id=ART171648&cat=SCANNERS&actp=LIST&showDraft=false

- http://gdlp01.c-wss.com/gds/5/0300034295/01/CR-150_CR-120_User_Manual_EN.pdf
(specifically, page 21)
