### ISSUE TITLE
Group History Job Does Not Log Archived Groups

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#3823]
### Description
A user archived some groups that belong to a group type with group history enabled. Upon archiving the groups, the data in the Groups table was accurate. However, after the nightly Group History job ran, we observed that the GroupHistorical table was not updated to reflect the group had been archived. 

### Steps to Reproduce
1. Confirm a group type has group history enabled.
1. Archive a group.
1. Manually run the Group History job.
1. Inspect the GroupHistorical table for the group you've archived.

**Expected behavior:**

I expect the GroupHistorical table to be updated to reflect that the group is indeed archived.

**Actual behavior:**

The GroupHistorical table was not updated.

### Versions
* **Rock Version:** 8.7 
* **Client Culture Setting:** EN-US

**Comment by nairdo** [comment]
I think this may have been corrected in either v8.8 or v9.  If anyone from the community would like to try to reproduce this in v8.8 and v9 please comment here when you do.

**Comment by kenmulford** [comment]
Just wanted to check back in and confirm this is still an issue in v8.9.
