### ISSUE TITLE
Transaction matching keyboard focus issue in V11

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#4300]
### Description

In transaction matching you used to be able to enter the amount of the check to each fund and hit the enter key to proceed to the next check. In V11 this no longer works.

### Steps to Reproduce

1. Scan some checks into Rock as a new batch
2. Open the batch and click on transaction matching
3. Apply check amount to an account
4. Hit enter key

**Expected behavior:**

After hitting the enter key you would proceed to the next check to match

**Actual behavior:**

It no longer proceeds to the next check to match

### Versions

* **Rock Version:** Rock McKinley 11.0 (1.11.0.3)

* **Client Culture Setting:** EN-US

**Comment by megilee** [comment]
We upgraded to v11.1 on Sunday night. Our finance person said this issue is still not fixed. We restarted Rock and she logged out/logged in/restarted. Any ideas or suggestions? Thanks!

**Comment by MichaelAllen** [comment]
We are also on 11.1 and still seeing this as well. (Chrome on Windows and Edge on Mac)

For now I have told my finance people to use `Alt + N` (win) or `Ctrl + Opt + N` (mac) as a workaround.

**Comment by adamhann** [comment]
Is this issues fixed yet? We are on 11.3 and I believe our accounting team is still having issues. In fact, after updating to 11.3 it seems that every time our finance worker matches a check and hits next we get an exception.

**Comment by megilee** [comment]
We are on 11.3 and the original issue of not being able to hit return/enter key to proceed has been fixed.

**Comment by nairdo** [comment]
@MichaelAllen If you are now on v11.3, can you also re-confirm or verify that you are still seeing or not seeing the issue?

**Comment by MichaelAllen** [comment]
I can confirm that it is working correctly for us on v12. I asked our fiannce director, and she is fairly certian it was working for us a few weeks ago on v11.3 as well, but I don't currently have a way to verify that.

**Comment by nairdo** [comment]
@megilee , @MichaelAllen  Thank you for the confirmation.  (@adamhann  It's likely that your running into a different issue -- since the enter key is posting back but then is causing an exception in your case.  So, we're going to re-close this issue, but please feel free to open a new issue with the details of the exception you are seeing.)
