### ISSUE TITLE
Activity “+” button in the connection request disappears after editing.

### ISSUE THREAD

**Issue by Angelaholt** [SparkDevNetwork/Rock#5130]
![Connection Request Missing Activity Add](https://user-images.githubusercontent.com/109543524/185977190-af5be806-58ff-4d8c-8999-bf5ea09faa50.png)

### Description
This issue is with the Connection Request Detail block. After editing the connection request by clicking the Edit button and saving the edits, the plus (+) button to add Activities disappears. The button also disappears if you add a new Activity, or if an existing Activity is deleted.

### Steps to Reproduce
1. Go to the Connection Request Detail block (e.g. https://rock.rocksolidchurchdemo.com/page/408?ConnectionRequestId=1)
1. Click the Edit button to edit the connection request.
1. Click either Save or Cancel on the edit screen.
1. The + button to add Activities to the connection request is no longer visible.

**Expected behavior:**

The + button should remain on the page so Activities can be added.

**Actual behavior:**

The + button to add Activities disappears.

### Versions
* **Rock Version:** 1.12.6.1 and 1.13.0.30 (Rock Demo)
* **Client Culture Setting:** en-US

**Comment by mikedotmundy** [comment]
Adding that this is also happening in v14.0, but is fixed upon a page refresh.

**Comment by GordonArber** [comment]
@mikedotmundy I wouldn't call a refresh "fixing it". Yes, the button reappears, but a refresh shouldn't be needed.

**Comment by billdeitrick** [comment]
@shauncummings This issue still seems to be present in 14.1 and 15.0. Should we expect the fix in a future release instead? Thanks!

Rock Solid Church Demo 14.1:
![2023-03-08_14-34-28](https://user-images.githubusercontent.com/4174527/223825182-520b2ff5-5a16-432b-b2b1-3c14950ac710.gif)

Pre-Alpha 15.0:
![2023-03-08_14-35-38](https://user-images.githubusercontent.com/4174527/223825651-5cf147e9-5cda-4afa-a4cd-04a74c55351c.gif)

**Comment by shauncummings** [comment]
Hi @billdeitrick.  Sorry you're still having trouble with this.  I'm not sure how Github tagged me in this one, but I'm going to reopen the issue and flag it for the development team to review again.

**Comment by billdeitrick** [comment]
Thanks for getting this squared away!
