### ISSUE TITLE
Child won't Register when Birthdays Match, ex. Twins

### ISSUE THREAD

**Issue by Gutseo** [SparkDevNetwork/Rock#5169]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

So we noticed an issue originating in our sports event registration, When Twins would register for the event it would only register one of the twins twice.

### Steps to Reproduce

1. Create an event registration with birthdate, gender, and address

<img width="714" alt="Screen Shot 2022-09-16 at 9 48 05 AM" src="https://user-images.githubusercontent.com/12351499/190691387-3f3a5c6e-8759-46a0-84e5-4df0a3116242.png">

2. With single registration, Register Child A and complete the registration. 

<img width="986" alt="Screen Shot 2022-09-16 at 9 08 06 AM" src="https://user-images.githubusercontent.com/12351499/190691391-969705e4-e0ed-49c1-8887-22ce4ad7fcf3.png">
<img width="1002" alt="Screen Shot 2022-09-16 at 9 08 11 AM" src="https://user-images.githubusercontent.com/12351499/190691345-254c3880-03bd-492c-accd-4a06e7e5faf9.png">

2.5. Go through registration again and Register Child B with the same Last Name, birthday and gender , at the end it says "You have registered Child A" or " You have registered Registrar or Parent Name"

<img width="993" alt="Screen Shot 2022-09-16 at 9 08 16 AM" src="https://user-images.githubusercontent.com/12351499/190691357-67d85943-fa1f-47a2-a634-44b5e69324d7.png">

4. Check the Event Registration and there are 2 registrations for Child A.

<img width="607" alt="Screen Shot 2022-09-16 at 9 47 09 AM" src="https://user-images.githubusercontent.com/12351499/190691375-7b470e18-d159-4990-a24c-b30a56359145.png">

5. With multi registration, Register Child A and complete the registration and Register Child B with the same birthday and gender, it says "You have registered Child A and Child A"

**Expected behavior:** 

The expectation is that both Child A and Child B would be registered for the event.

**Actual behavior:** 

Only Child A was registered, but twice. it also updates the record with the new information.

### Versions

* **Rock Version:** [12.8 in our installation 13.4 on the demo site]  
* **Client Culture Setting:** [en-US]

**Comment by abpena1979** [comment]
Fixed in 13.4 with [12050dd](https://github.com/SparkDevNetwork/Rock/commit/12050dd68ea596d3228b8367a8dc34c1ee47a032)

**Comment by Gutseo** [comment]
We are still seeing the error on the dev server and our 13.6 dev installation.

**Comment by abpena1979** [comment]
@Gutseo  - Let me take another look and follow-up.

**Comment by ethan-sparkdevnetwork** [comment]
@Gutseo Hello. I tried to replicate this but have not been able to. Could you provide a screenshot of the "Details" section of the registration template? The Rock [demo site](https://rock.rocksolidchurchdemo.com/) is on v14.2, can you check if the issue exists there?

**Comment by Gutseo** [comment]
it looks like v14 resolves the issue, sorry I didn't test it again when the demo site upgraded :).
