### ISSUE TITLE
Obsidian Registration Entry Block Error Initializing Block

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5883]
### Description

I don't know if this is a bug but I just upgraded from v15.5 to v16.4, I stop on 16.4 per request from Simple since there is an issue with their system. I apologize if this is not the place to post something like this but all of our active registrations just stopped working. 

It seems to be a javascript issue. 
![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/c90c4b65-63d9-413c-bb48-858c31072e89)
![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/aa078477-bc80-4a0b-addb-52fd59c3488d)

### Actual Behavior

Actual Behavior

### Expected Behavior

Expected Behavior

### Steps to Reproduce

- Upgraded from v15.5 to 16.4

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@frogydiak Please confirm that your issue is now resolved and I will close this issue.

**Comment by frogydiak** [comment]
No, it is not. I just cleared my browser cache and the error is still there. I need help please! We have 15 active registration right now and most of it are paid events.

**Comment by frogydiak** [comment]
Any idea why rockPage.js would raise an error?

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/f34e8211-cc5e-4508-b952-53a402974677)

**Comment by chead4** [comment]
@frogydiak Can you share a screenshot of your Registration Entry block settings/Advanced Settings and your registration template, Terms/Text - registration instructions?

**Comment by frogydiak** [comment]
@chead4 Please refer to: https://chat.rockrms.com/channel/events-registrations?msg=M8dE2fK6vGAtDWDnM

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/67046f46-19c4-468a-b540-6301592cea7d)
![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/c491abcb-1826-423a-9fe9-294ee620781c)

@bmurphy-dev suggested to restart IIS (again), clear anything I added to the block preHTML. I only have this originally in PreHTML:

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/c8cd748d-05fa-4cc8-81e5-1151ba8561c1)
So, I removed the CSS and HTML, restarted IIS (again), cleared my browser cache, and it worked. But not in mobile devices. I can confirm this in both iPhone (Safari, Chrome, and FF) and Android devices (Chrome).

**Comment by frogydiak** [comment]
UPDATE! I just noticed that if I'm in the same network as the servers (IIS and SQL), I don't get the error. Nothing was changed in our firewall since or after the upgrade. Is there a key thing that was changed in v16 that might affect accessibility in terms of in networking? We do use CloudFlare but there are no rules or WAF is disabled. I just disable Argo Routing just incase that's what causing it.

Thoughts?

**Comment by chead4** [comment]
@frogydiak 

Thanks for sending that information above.  No, there were no changes in v16.4 for networking.  We took a look at the information that you provided and have a few more questions for you.

1. For the Text/Terms that you have shared above, is this the Registration Confirmation Text?  and is the Registration Instructions blank? 
2. On the Registration Instance, please include a screenshot of the Registration Messages section.  We would like to see what you may have entered in Registration Instructions, Additional Reminder Details and Additional Confirmation Details.
3. Do you have anything unique with currency in your environment?  
4. What is your global currency value?

**Comment by frogydiak** [comment]
@chead4 

Thank you for looking at this with me. I have the urge to rollback to yesterday's checkpoint but I'll wait until you guys says "we don't have a clue what's going on."

> 1. For the Text/Terms that you have shared above, is this the Registration Confirmation Text?  and is the Registration Instructions blank?

Yes, it is blank:
![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/746c7547-036b-4616-a610-f3b3dad86992)

> 2. On the Registration Instance, please include a screenshot of the Registration Messages section. We would like to see what you may have entered in Registration Instructions, Additional Reminder Details and Additional Confirmation Details.

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/7cb910e0-4289-4bf9-9dea-a9128f3f2acb)
Just plain text with p tag.

In the template side, under Confirmation Email, I noticed a line that says "16.4 fix" but I don't see any code to fix something:
![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/ea3867f4-3fc5-4bfa-b826-9085b409480a)

> 3. Do you have anything unique with currency in your environment?
Are you asking about the Global Attributes? I have not touched it since we are in Pasadena, CA so we are only using $ USD.

> 4. What is your global currency value?
Where do I see this settings? See #3.

**Comment by chead4** [comment]
@frogydiak 

Yes, it was the Global Attribute I was asking about.  This is the first time we have heard of this issue and we are not sure why it is occurring.  I have tried to recreate using information you have provided in my registration template on v16.4 and I don't get any errors and I am able to register.

**Comment by frogydiak** [comment]
@chead4 Is there any changes in v16.4 that is related to Group placement? All of our registration is configured to an Event Type group.

**Comment by chead4** [comment]
@frogydiak There were no Group Placement or Group in Linkages updates in v16.4 that I could see after reviewing the [release notes](https://www.rockrms.com/ReleaseNotes#v16.4).  I've been discussing the issue internally with the development manager and the team throughout the day and unfortunately we were not able to recreate the issue. At this time you may want to explore other options.

**Comment by JimMichael** [comment]
I really think this is a Cloudflare issue of some sort, based on a similar error someone else behind Cloudflare recently had. That would explain why it’s so rare (compared to the entire Rock ecosystem that has upgraded to v16 without issue). 

https://chat.rockrms.com/channel/general?msg=Bu2fAtgNvQi7WbNnk

That would also explain why it works fine when you’re on the local network.

**Comment by jonedmiston** [comment]
@JimMichael  that's an interesting thought. @frogydiak are you able to purge your Cloudflare CDN? Perhaps an old version of the .js files is cached in the CDN. If so you might need to ensure the CDN is varying the cached files using the full querystring.

**Comment by frogydiak** [comment]
@JimMichael I'm speechless! It turned out Purge Everything in CloudFlare does not work as what it says. I disabled it instead and it seems to be working now.

@jonedmiston Thank you! CloudFlare CDN must be serving the old .js file that causes the error. After making sure I don't get an error with cache being disabled, I created a rule this time to only serve cache if no query string and follow origin TTL.

@chead4 Thank you so much for your help today!

**Comment by chead4** [comment]
@frogydiak That is great news that you got it working.  Thank you to both Jon and Jim for jumping in as well.  I will be closing this issue at this time.
